# Generated by Django 3.2.5 on 2023-07-22 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lanternDie', '0002_profiles_delete_lanterndie'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profiles',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kills/')),
                ('caption', models.CharField(max_length=140)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
