# Generated by Django 3.2.5 on 2023-07-23 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lanternDie', '0003_auto_20230722_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='killCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user',
            field=models.OneToOneField(default='01', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
