# Generated by Django 4.2.4 on 2023-08-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanternDie', '0004_auto_20230723_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kill',
            old_name='image',
            new_name='image1',
        ),
    ]
