# Generated by Django 4.2.4 on 2023-08-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanternDie', '0005_rename_image_kill_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='profPic',
            field=models.ImageField(default='fly.webp', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='kill',
            name='image1',
            field=models.ImageField(upload_to='kills'),
        ),
    ]
