# Generated by Django 4.2.4 on 2023-08-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanternDie', '0007_rename_image1_kill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kill',
            name='image',
            field=models.ImageField(default='static/empty_post.jpg', upload_to='kills'),
        ),
    ]
