# Generated by Django 4.2.4 on 2023-08-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanternDie', '0008_alter_kill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profPic',
            field=models.ImageField(default='fly.webp', upload_to='profile_pics/'),
        ),
    ]
