# Generated by Django 4.2.4 on 2023-08-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanternDie', '0009_alter_profiles_profpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='profPic',
        ),
        migrations.AddField(
            model_name='profiles',
            name='profPicKey',
            field=models.CharField(default='fly.webp', max_length=500),
        ),
        migrations.AlterField(
            model_name='kill',
            name='image',
            field=models.ImageField(default='empty_post.jpg', upload_to='kills'),
        ),
    ]
