# Generated by Django 4.2.4 on 2023-08-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanternDie', '0010_remove_profiles_profpic_profiles_profpickey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='profPicKey',
        ),
        migrations.AddField(
            model_name='profiles',
            name='profPic',
            field=models.ImageField(default='fly.webp', upload_to='profile_pics'),
        ),
    ]
